version: "3.8"
services:
  php:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: notification_api
    volumes:
      - ../:/var/www
    ports:
      - "8080:80"
    environment:
      DB_HOST: mysql
      DB_NAME: notification_system
      DB_USER: root
      DB_PASS: password
      REDIS_HOST: redis
      JWT_SECRET: secret
      JWT_ISSUER: local.com
      SMTP_HOST: mailhog
      SMTP_USER: example
      SMTP_PASS: example
      SMTP_PORT: 1025
    depends_on:
      - mysql
      - redis
      - mailhog

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: notification_worker
    command: php /var/www/worker.php
    environment:
      DB_HOST: mysql
      DB_NAME: notification_system
      DB_USER: root
      DB_PASS: password
      REDIS_HOST: redis
      JWT_SECRET: secret
      JWT_ISSUER: local.com
      SMTP_HOST: mailhog
      SMTP_USER: example
      SMTP_PASS: example
      SMTP_PORT: 1025
    depends_on:
      - mysql
      - redis
      - mailhog

  scheduler:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: notification_scheduler
    command: php /var/www/scheduler.php
    environment:
      DB_HOST: mysql
      DB_NAME: notification_system
      DB_USER: root
      DB_PASS: password
      REDIS_HOST: redis
      JWT_SECRET: secret
      JWT_ISSUER: local.com
      SMTP_HOST: mailhog
      SMTP_USER: example
      SMTP_PASS: example
      SMTP_PORT: 1025
    depends_on:
      - mysql
      - redis
      - mailhog

  websocket:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: websocket_server
    command: php /var/www/ws-server.php
    environment:
      DB_HOST: mysql
      DB_NAME: notification_system
      DB_USER: root
      DB_PASS: password
      REDIS_HOST: redis
      JWT_SECRET: secret
      JWT_ISSUER: local.com
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: notification_system
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
